# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import startx_service_pb2 as proto_dot_startx__service__pb2


class StartxServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MessageStream = channel.unary_stream(
                '/grpc.StartxServer/MessageStream',
                request_serializer=proto_dot_startx__service__pb2.User.SerializeToString,
                response_deserializer=proto_dot_startx__service__pb2.Note.FromString,
                )
        self.SendNote = channel.unary_unary(
                '/grpc.StartxServer/SendNote',
                request_serializer=proto_dot_startx__service__pb2.Note.SerializeToString,
                response_deserializer=proto_dot_startx__service__pb2.Empty.FromString,
                )
        self.Register = channel.unary_unary(
                '/grpc.StartxServer/Register',
                request_serializer=proto_dot_startx__service__pb2.User.SerializeToString,
                response_deserializer=proto_dot_startx__service__pb2.Empty.FromString,
                )


class StartxServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MessageStream(self, request, context):
        """This bi-directional stream makes it possible to send and receive Notes between 2 persons
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StartxServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MessageStream': grpc.unary_stream_rpc_method_handler(
                    servicer.MessageStream,
                    request_deserializer=proto_dot_startx__service__pb2.User.FromString,
                    response_serializer=proto_dot_startx__service__pb2.Note.SerializeToString,
            ),
            'SendNote': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNote,
                    request_deserializer=proto_dot_startx__service__pb2.Note.FromString,
                    response_serializer=proto_dot_startx__service__pb2.Empty.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=proto_dot_startx__service__pb2.User.FromString,
                    response_serializer=proto_dot_startx__service__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.StartxServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StartxServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MessageStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.StartxServer/MessageStream',
            proto_dot_startx__service__pb2.User.SerializeToString,
            proto_dot_startx__service__pb2.Note.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.StartxServer/SendNote',
            proto_dot_startx__service__pb2.Note.SerializeToString,
            proto_dot_startx__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.StartxServer/Register',
            proto_dot_startx__service__pb2.User.SerializeToString,
            proto_dot_startx__service__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
